apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: eahftp3sf-python 
  janus-idp.io/tekton: eahftp3sf-python
  backstage.io/kubernetes-id: eahftp3sf-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eahftp3sf-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  