apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: eahftp3sf-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: eahftp3sf-python 
  name: eahftp3sf-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: eahftp3sf-python 
